name: Watch_qiita

on:
  schedule:
    - cron: '*/10 * * * *' # cronで定期実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # おまじない

      - name: Setup python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Pythonのバージョン指定

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # pip install pandas
          # pip install pytz
          # pip install matplotlib
          # pip install numpy

      - name: Run main.py
        run: |
          python main.py
