name: Watch_qiita

on:
  schedule:
    - cron: '0 21 * * sun' # cronで定期実行

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
      API_KEY: ${{ secrets.API_KEY }}
      API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py
